# Use the official Python 3.10.9 image
FROM python:3.9.16

# Copy the current directory contents into the container at .
COPY ./requirements.txt /app/requirements.txt

# Install requirements.txt 
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Set the working directory to /
WORKDIR /app

# Start the FastAPI app on port 7860, the default port expected by Spaces
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]