# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create HTML report from Jupyter Notebook

on:
  #schedule:
  #  - cron: "0 0 * * *"
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    # Assigning permissions to jobs  # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # Modify the default permissions granted to GITHUB_TOKEN.
    permissions: write-all

    steps:
        - uses: actions/checkout@v3
  
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ipython ipykernel nbconvert nbclient
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: executing jupyter notebook & export html report
          run: |
            echo today_date=$(date +'%Y-%m-%dT%H:%M:%S') >> GITHUB_ENV
            jupyter execute housing_data.ipynb
            jupyter nbconvert --output-dir='./report' --output 'report_${today_date}' --to html housing_data.ipynb 

        - name: Commit the changes to this github repo
          uses: mikeal/publish-to-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
            BRANCH_NAME: 'main'