# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create HTML report from Jupyter Notebook

on:
  #schedule:
  #  - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
  
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ipython ipykernel nbconvert nbclient
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: executing jupyter notebook & export html report
          run: |
            jupyter execute housing_data.ipynb
            jupyter nbconvert --output-dir='./report' --output day1 --to html housing_data.ipynb 
