# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Web scraper environment setup

on:
  schedule:
    - cron: "20 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Assigning permissions to jobs  # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # Modify the default permissions granted to GITHUB_TOKEN.
    permissions: write-all
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Scrape
        run: |
          ## Change the script's permissions to allow execution
          chmod +x scrape_housing_data/script.py
          # Now you can run your script like this:
          python3 scrape_housing_data/script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Output:
        # [Expected output from your script]
      
      - name: Commit the changes to this github repo
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
          BRANCH_NAME: 'main'
