# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Web scraper environment setup

on:
  schedule:
    - cron: "20 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    # Assigning permissions to jobs  # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # Modify the default permissions granted to GITHUB_TOKEN.
    permissions: write-all
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      #- name: Test with pytest
      #  run: |
      #    pytest

      - name: Scrape
        run: |
          ## Change the script's permissions to allow execution
          chmod +x src/script.py
          # Now you can run your script like this:
          python3 src/script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Output:
        # [Expected output from your script]
      
      - name: Commit the changes to this github repo
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
          BRANCH_NAME: 'main'
